
export const NATIVE_NOTIFY_APP_ID = Number(
  process.env.EXPO_PUBLIC_NATIVE_NOTIFY_APP_ID!
);

export const NATIVE_NOTIFY_APP_TOKEN =
  process.env.EXPO_PUBLIC_NATIVE_NOTIFY_APP_TOKEN!;

// Helper flag
export const NATIVE_NOTIFY_ENABLED =
  !!NATIVE_NOTIFY_APP_ID && !!NATIVE_NOTIFY_APP_TOKEN;
